#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source local changes first so we may influence Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zrclocal" ]]; then
  source "${ZDOTDIR:-$HOME}/.zrclocal"
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
